defaults:
  attach: &attach
    attach_workspace:
      at: .
  getDeps: &getDeps
    restore_cache:
      key: yarn-cache-{{ checksum "yarn.lock" }}
  job: &job
    working_directory: /tmp/project
  nodeJob: &nodeJob
    <<: *job
    docker:
      - image: circleci/node:12.18

version: 2
jobs:
  install:
    <<: *nodeJob
    steps:
      - checkout
      - *getDeps
      - run: yarn install --frozen-lockfile
      - run:
          name: Snyk
          context: snyk
          command: curl -sL https://raw.githubusercontent.com/segmentio/snyk_helpers/master/initialization/snyk.sh | sh
          environment:
            SNYK_FAIL_ON: upgradable
            SNYK_SEVERITY_THRESHOLD: high
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/core/node_modules
            - packages/integrations/node_modules
            - packages/test-app/node_modules

  lint:
    <<: *nodeJob
    steps:
      - checkout
      - *getDeps
      - run: yarn commitlint-circle
      - run: yarn lint

  test-core:
    <<: *nodeJob
    steps:
      - checkout
      - *getDeps
      - run: yarn core test
      - run: yarn codecov

  build-core:
    <<: *nodeJob
    steps:
      - checkout
      - *getDeps
      - run: yarn core build
      - persist_to_workspace:
          root: .
          paths:
            - packages/core/build/**/*
            - packages/core/build/package.json

  build-integrations:
    <<: *nodeJob
    steps:
      - checkout
      - *getDeps
      - run: yarn integrations build
      - persist_to_workspace:
          root: .
          paths:
            - packages/integrations/build/**/*

  build-test-app:
    <<: *nodeJob
    steps:
      - checkout
      - *getDeps
      - *attach

      - run: yarn test-app build
      - persist_to_workspace:
          root: .
          paths:
            - packages/test-app/project

  test-android:
    <<: *job
    docker:
      - image: circleci/android:api-26-node
    steps:
      - checkout
      - *getDeps
      - *attach
      - run: yarn test-app test:android

  test-ios-vanilla:
    <<: *job
    macos:
      xcode: '11.5.0'
    steps:
      - checkout
      # macOS VMs doesn't support Docker based caches
      - run: yarn install --frozen-lockfile
      - *attach
      - run: brew update-reset
      - run: brew tap wix/brew
      - run: brew install wix/brew/applesimutils

      - run: yarn test-app test:ios:vanilla

  test-ios-cocoapods:
    <<: *job
    macos:
      xcode: '11.5.0'
    steps:
      - checkout
      # macOS VMs doesn't support Docker based caches
      - run: yarn install --frozen-lockfile
      - *attach
      - run: brew update-reset
      - run: brew tap wix/brew
      - run: brew install wix/brew/applesimutils

      - restore_cache:
          key: cocoapods-specs
      - run: yarn test-app test:ios:cocoapods
      - save_cache:
          key: cocoapods-specs
          paths:
            - ~/.cocoapods
  publish:
    <<: *nodeJob
    steps:
      - checkout
      - *getDeps
      - *attach
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - run: sudo npm config set @segment:registry https://registry.npmjs.org/ --global
      - run: yarn deploy

workflows:
  version: 2

  build_test_and_publish:
    jobs:
      - install:
          context: snyk
          filters:
            tags:
              only: /.*/
      - build-integrations:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - build-core:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - build-test-app:
          requires:
            - build-core
            - build-integrations
          filters:
            tags:
              only: /.*/
      - test-core:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - test-android:
          requires:
            - build-test-app
          filters:
            tags:
              only: /.*/
      - test-ios-vanilla:
          requires:
            - build-test-app
          filters:
            tags:
              only: /.*/
      - test-ios-cocoapods:
          requires:
            - build-test-app
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - publish:
          context: snyk
          requires:
            - build-test-app
            - test-android
            - test-ios-vanilla
            - test-ios-cocoapods
            - test-core
            - lint
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.+)?/
