defaults:
  requiresInstall: &requiresInstall
    requires:
      - install
  requiresTestApp: &requiresTestApp
    requires:
      - build-test-app
  attach: &attach
    attach_workspace:
      at: .
  getDeps: &getDeps
    restore_cache:
      key: yarn-cache-{{ checksum "yarn.lock" }}
  job: &job
    working_directory: /tmp/project
  nodeJob: &nodeJob
    <<: *job
    docker:
      - image: circleci/node:8

version: 2
jobs:
  install:
    <<: *nodeJob
    steps:
      - checkout
      - *getDeps
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/core/node_modules
            - packages/integrations/node_modules
            - packages/test-app/node_modules

  lint:
    <<: *nodeJob
    steps:
      - checkout
      - *getDeps
      - run: yarn commitlint-circle
      - run: yarn lint

  test-core:
    <<: *nodeJob
    steps:
      - checkout
      - *getDeps
      - run: yarn core test
      - run: yarn codecov

  build-core:
    <<: *nodeJob
    steps:
      - checkout
      - *getDeps
      - run: yarn core build
      - persist_to_workspace:
          root: .
          paths:
            - packages/core/build/**/*

  build-integrations:
    <<: *nodeJob
    steps:
      - checkout
      - *getDeps
      - run: yarn integrations build
      - persist_to_workspace:
          root: .
          paths:
            - packages/integrations/build/**/*

  build-test-app:
    <<: *nodeJob
    steps:
      - checkout
      - *getDeps
      - *attach

      - run: yarn test-app build
      - persist_to_workspace:
          root: .
          paths:
            - packages/test-app/project

  test-android:
    <<: *job
    docker:
      - image: circleci/android:api-26-node8-alpha
    steps:
      - checkout
      - *getDeps
      - *attach

      - run: yarn test-app test:android

  test-ios:
    <<: *job
    macos:
      xcode: "9.4.0"
    steps:
      - checkout
      # macOS VMs doesn't support Docker based caches
      - run: yarn install --frozen-lockfile
      - *attach
      - run: brew tap wix/brew
      - run: brew install wix/brew/applesimutils

      - restore_cache:
          key: cocoapods-specs
      - run: yarn test-app test:ios
      - save_cache:
          key: cocoapods-specs
          paths:
            - ~/.cocoapods
  publish:
    <<: *nodeJob
    steps:
      - checkout
      - *getDeps
      - *attach
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - run: yarn deploy

workflows:
  version: 2

  build_test_and_publish:
    jobs:
      - install
      - test-android: *requiresTestApp
      - test-ios: *requiresTestApp
      - test-core: *requiresInstall
      - lint: *requiresInstall
      - build-integrations: *requiresInstall
      - build-core: *requiresInstall
      - build-test-app:
          requires:
            - build-core
            - build-integrations
      - publish:
          requires:
            - build-test-app
            - test-android
            - test-ios
            - test-core
            - lint
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.+)?/
            branches:
              ignore: /.*/
