version = 1


[install]
node.pkg-path = "nodejs_20"
yarn.pkg-path = "yarn-berry"
yarn.version = "4.12.0"


[vars]

[hook]
 on-activate = '''
    yarn
 '''


[profile]


[services]
# myservice.command = "python3 -m http.server"


[include]
environments = [
    { dir = "../common" },
]


[build]
# [build.myproject]
# description = "The coolest project ever"
# version = "0.0.1"
# command = """
#   mkdir -p $out/bin
#   cargo build --release
#   cp target/release/myproject $out/bin/myproject
# """


[options]
