name: E2E (Latest)

on:
  workflow_dispatch:

concurrency:
  group: e2e-latest-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run-e2e-ios:
    uses: ./.github/workflows/ios-e2e.yml
    with:
      target: max
    secrets: inherit

  run-e2e-android:
    uses: ./.github/workflows/android-e2e.yml
    with:
      target: max
    secrets: inherit
